import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'package:audioplayers/audioplayers.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:noa/models/app_logic_model.dart' as app;
import 'package:noa/noa_api.dart';
import 'package:noa/pages/pairing.dart';
import 'package:noa/style.dart';
import 'package:noa/util/alert_dialog.dart';
import 'package:noa/util/check_internet_connection.dart';
import 'package:noa/util/sign_in.dart';
import 'package:noa/util/switch_page.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:webview_flutter/webview_flutter.dart';

TextSpan _clickableLink({required String text, required String url}) {
  return TextSpan(
    text: text,
    style: textStylePink,
    recognizer: TapGestureRecognizer()
      ..onTap = () async {
        if (await canLaunchUrl(Uri.parse(url))) {
          await launchUrl(Uri.parse(url));
        }
      },
  );
}

Widget _loginButton(
  BuildContext context,
  WidgetRef ref,
  String image,
  Function action,
) {
  return GestureDetector(
    onTap: () async {
      try {
        ref.read(app.model).loggedIn(await action());
      } on CheckInternetConnectionError catch (_) {
        if (context.mounted) {
          alertDialog(
            context,
            "Couldn't Sign In",
            "Noa requires an internet connection",
          );
        }
      } on NoaApiServerError catch (error) {
        if (context.mounted) {
          alertDialog(
            context,
            "Couldn't Sign In",
            "Server responded with an error: $error",
          );
        }
      } catch (_) {}
    },
    child: Padding(
      padding: const EdgeInsets.only(bottom: 20),
      child: Image.asset(image),
    ),
  );
}

class LoginPage extends ConsumerStatefulWidget {
  const LoginPage({super.key});

  @override
  ConsumerState<LoginPage> createState() => _LoginPageState();
}

class _LoginPageState extends ConsumerState<LoginPage> {
  late bool showWebview;

  Uint8List decodeBase64String(String base64String) {
    List<int> bytes = base64.decode(base64String);
    return Uint8List.fromList(bytes);
  }
  Future<void> playByteArray(Uint8List byteArray) async {

    try {
      AudioPlayer audioPlayer = AudioPlayer();
      audioPlayer.play(BytesSource(byteArray));
    } catch (e) {
      print("Error playing audio: $e");
    }
  }
  @override
  void initState() {
    String base64String = "//PkxABhnDnYAtZwbDpelRceTYdiUcY8aveEujycjqNjPnDoSjXKj0mHHzpRZu3ZDREMzTzFBMlk4YTZTM80yyzLHNgi1iYiEgu4WcLIFtEfEJZeNQdU6gaEtMNU6Y5ZAwCMQizBchBwv4ABAYAGGWTLbpFsTS/RTWHQlloEHC4BcRTRYRYjXGGJFsHa2sOqdQNQdd7E12KkXQ/i5EVEVFcQ477Ky/6ANY7D1A0i1N1AC7heBFRQRiDDF2LsWOu9QNMdMddd+hctYRQRdigCxGcLsXYuxMNU6gaQ6g7E1zrHZ2sRrjuOQwxUjLGsNcctnbX3LZ278bjbtpiMEfx/HYWEXQ/j+M7Z25b/s7i77s7d9hipGIM4dxrDEGsLsUHUDWOw9U7O1zsTZ2kQoIuxrkUqOAsIqRItQdibltbWHVOu9ibEF2LsXYuxrj+NYcSNsrXexN33/ctrbX2GJCIqJEMQhyMQw5C71TrvXeu9d7E37l9JKH8lkMMMcSWUkrjcvjdO+7D2JwPUdhyJY+iJiDi6IooRg4YIQYJ4ESmHIiixllAfAaUzB4nEatB5nEYjSYc0WDGTvDnJqVR9AYdiUrmNpgqpngzh5Q0hvLV5wuUBrQ0xjUUpuELBj6r5oibp//PkxEx0PDnQCP9ybISByUHKYljCYEAoYEBWlCZRhqDEwxmrA1AVgCEwasGOG9aDijQLKgoUVAXAEJEBYilB1wGiFvxgARgM3CLgd2W2Ay4CYfBMQGgggFOgEikXpkDKUCMICusHYNbYAX2pV4JKkSiW4EFM8NkJbdS4FHmeKDCAN8kkBjxVEqnAE0wBTYHQfL9DxosrAj6qZA4pUrK31Yiv5MRl7XXWMAESTBAyyAFGk+9Y0koOMDKUKqpjkwSgi5mnuuXwW6jmWiHgQoYjey1GBKyG2BJbs0T4TTYml4uRTeIDoCnDliEd/Bg1eT2AQZbRdllKl7cVXp3LwVgIg2igwZaiRS+XZVOwkiCY4/i427MNS+EIYoQ1CPqGFz4EUBQ/n0IYGW+nW5SSat0PIbukxV7ldrifJuMFuY1VoKcD4F5VuuG3BrTDoDZOwMunDUPIqFAoUFS3U7X0hYzR5knlLE8mlIdmpoHS8OAlqOKOYWIMwEtes1ZIYvClrv08KGCGC7mGUzQGQkIDXkOJYDZrkCAjALAAkwIACeMHjCqzBDSoQ1ngrBMSDKIjEQw8Ewx0OLMznRzTC+z8Mx7wtKMlSGGDCrRrUyXkelMC/BSjBFwW4wLwHnMQZFBQEf2G//PkxE53FDoARP803A+IWuYZKE/mBKhRh8IXmuQoZ2PhkgVGQBwDhGAhG0uaL+J8GJAAYRBqGwBA6RcNwtgCdDBFYJmRYo9v0sGyd7ZiOsplT/svmHYnMmZvQW0sCEBhAPCoFDgmXUVhLON6wCG4/DCci7H0YsYGERiISGJhUYaARg4jGekgaGNRmI2GlyuDQ0RBFyorffdIwwxg2q8zIczbU1YEGBkQTEgzFjxIWxtTdpT8ryRBVfH1VjAh1MlIILwyl8hY4LjL0fZUhf9nIORp8GLLqwgoQ7SmDOY+80y39h/5qIsgjDuTDqUsmYI/dI+8MTzEJbL4bXPA9PLI4tBekovK3tfnIpEFyPI8b9x+wpm1+bcN34zGH4fxrlFT08jooDlTOGuJULcbouxa7MFSKaLomIg7mTc3feZMBIRscMo9t8udQMvGg+19W9k4wGJRZhgBkAhiAA6TMaDMOLBQMwpNPZNqdGgpm1Zo3pySJg0aQYGVmHLllDHiVdiwMxwoQgjPEhCXMoEhgADAEVNmxNWbMSnAUsAFlUCQFxgwhDGqMKwYFw9J+plZmQ6LWZtsKBjAiBmXVYaZpQC5gdxvHDBFWYD6phuUPYGjIAQa052pj1hsmMmEyYoIkhkU//PkxERrBDocIPafGp5ZmADnGM+N0ahgn5m2j9mGYR0Yog4JmGl4mMoHoYTQFwKBLMCABYwCQLTBFAtNKRYeYEaZwQly9ql5cuHgaBTTf4unPsQbsyRrbT7LspgLCPw4DWH0TAbgtMwQoxQw2TQ4A4cGCqE5LE6K0EiTSEAAFNKdUoAodEpGQv+rMWgCgwiSA4gQCAqWOqmMkZO2bPxgObPJio6bMSbdcVKsiQCGXEsSMcKKg8yYsuHA5mjQGEpQlk2VK4txZ2IcbctUV/CZGxkfyqhmUS4hN1I0lbeHaJLt7Fu9cZoMC7enHBbbEJeKiJAHALCRZJAZ45hQAa5MxbC+nkNQV8Z50mWT8wrGmSxD2IuJlLUAt49SBJ2kFycRf0MeuasjR2pRJo70YiWc8Eif0dlTpPkTHblyfCvflEc0dSGGgVYeqiJccijXCmZzi2aTYTcsA9Iwx45D9F8hwdQrpLDILEnjpCQrAhQ9YMIwCdKkiIQMCYBswVwSDHUAzMQlIs0EErjFnBdMi4p0xji0jS2YmMkoJ8ymSlDJWNcM+RM42lxXTOSSnMj5jI0eERjPIA8BpPmV9NG/iiGcAfGCRwmmqtH2ECmNx5nQQmGZh4m6PunUZYmbK4mmYgmi//PkxGtwFDosCvd0rIgBioFih5EBhiWSZhWAZiSIJMDwOchA8x6MLmASBMkCLLFZIzJ1M4UMmTHkRsDETIEEKVLjADAUMGjoJAg4iYYUZsyAQyCU4D4M0GV8mOjG4ZGycGzMhjQxRIygMCBzDhDUJDPGEmDQFAULEYQIcFEkyi8SQGXVmtJmLRhQePoQiAaIQXKZuDQBmjRISMcDGBxe0yYEcDCEuaQUhaRGQYELotSUsXwXgVvYO8GEsleEMNMWm6ynShqZ7XVLk4Ei4NYO/9ZurbLspamUYvxOfid+VyKUz8cvTTwS1n8bd+HKZnDIGG03WrNYfx0Hte2OMQssAcSMR2Zhh7YnFocgC9EmmSxw3XfTVjdjBw6Otdu00YtXd2ojap5ZepaObf/s81yMwNEmywPEpyBH/zk1DGoxyip2mUUWhizZvQQ6DWHxgeRQ278AVXQiNNOPu1KKWqJ+49fmFQQBqYPwDxgLBBmU25GafA4ZhABIGFaLmZ75lZm8C7mAmCUYPJEJlhniGOeMgYyYV5h3nDhlf5pAF3mOQNAZtagpo4k3AIL0xBhzCjwTrtYgCVBjgBhs5IBo0cxiC6xwo9hs8r56HHRoDHZrquJmWHRgkDRkqNJgSNRkYKYC//PkxH14pDo0APd2yC+BVeaqWmXGxkpwZcBGSCwUQQsCmRmKvyZhMeIAMDgkBDkMEloOLzDhhvTIAlAMFSIHBglViJGMUGBieMRFwq8hUGM/hzYgQyEIMAChksEJGYmimTmICljJBwMSDKRMLGBjIYASswwPMpYDBDIwAGAVgZNDCEyMyAgglJo8SSwKIrMABqBAIAAaWoKEyy7Q34JQtLlcCQ6t5asWC0D0T01SwAAIzgZcQwCGABTvgIfeKjMTA2iGCAgECEDC+adSmDZywEIsSUtmEA7K2dOpBzzuCve1I3MkT7TCgcG0sYdVos67igEaWEXQ3Fnq7WQNcplBIdjSW9PSX1yaeZ0pa9srY80hyLkGMMkqm7UmxJeKWP3DjXHpk70PowS47bLHshifkjaPm0tl6uY+28DMAdiSsravDrW4u/kJvSmnoqKBYCg144hUnJe+TdIPcuo6ViIyKGHma/UbJWvZy6ejsmlE9cxlsdUMBTXe8vsLG48k4TFQJAoLM4zcycBzCQdMsej1oEygtMIJDIGMz8sELCYnVn3zRijMZgZHdVRvo8Y8zGqEBpqWboEmtHxhjMZWHGIiphlIbRQhy2bacD1YGGwGATCwUHAKEYGWCDQ4YAgIAEcX//PkxG1pJDpgNubyWJh4pI1OIvE+IQM44cU0lqS9s1YqNMGAW/X8/KFSa5bUkBMo0ECEzI6SXNQmFt3nLnFn1TJElUR1lBi0xYBo4WgJHhFbkwhIl1WUoUCwV9YFyJ55WWyKtIGPv1BbNGTxVeC/liFQQs4LDlqBmAuGZDBIQAlQBIc4ICmKjZ6gjUZpCmeeSgmEIEMMVCpKiT+ipIFCR6bAmi1Rv1xtgaGq+dYfFm3hLZ1YnYa22NUjWHoSTbkvdHVujby9ASj1dYCms5Ljtea4qSAWhpzKzxeA2Al8nAbgNCJFPIjwyZSDsLaIg3aVwu9zUJiZazHfBICb67WmloVVninWSsngNS2Ny6AG/azBbg2l0wM1JzXnetx34tPvLW415VWfijjbqNxhKnUrfadYE7NyXe16QvS/0ieK88sYiriSpQA4FQCBGB+YJhhxpegAGCCCMYWpKpjMchioAJjCnZn2bZjIG5kCfpryrhnGSBjOI5oEgBoCaxpAGp3+f50dM5kI5Jom6xlOL5n6SplGpxoSbhgylhmqPxnUrZig6oENQ0gd0yEUkyiEQxaJExmEMxfAEwmAkDDWYDhEaWZzDj4IKFIvTZiL/q0gQZwiZgwgYgsCQAF2kFC3pbpJ//PkxJtxrDo8BvdyPFBhpdEt3Gy1SkxksBGhy5c07KSEwSnPOA5Uwc+kkfI6E4KOrkM9MUOF4ytMkDONROwlZAHBtil/jrbJk1bQWsyhSRjhM/aY2V1V1Raaa1D7ZVqsAdlMAvAu6WF9l3kKRnKpygYQctHkU8DfjR7WGCSUA4QAMprFKETdRAxz5GcOaIkiHTyyReMLhgINuCvUYn5TvdSD6Npz6xNsTjxhzJiTS5Me/ArUnlZKvBPBdzA2bNIjq6IpIWSsI6o8l4lsnRIUEzTV+QKoAtxlCxHYgUtUm2g4zlwRoh+XYbRfqt8MKKNBUIcqKJqorNEYktlkjvTy0X1YBJmdMXVtl6pm6sxeBwIkteKSRx2NxxrTKHvs2FYqrOYKvQinyTNfRr0zLGvMFgyWv7O0EZqPAjAIBPMB8VwzUJLjUzHIMEIbI0JD2zSQdzUaMj5TQzN1BDERSzQAaDL09TXdPTZ5iQKk4+YZu9oZoFbxxdkZipIpjEPRuJJ5jW0ZmUghqu1JmWyphCQ52EJxm0JZoi4pwUk5gqPZrGOY9mnCN5hB+HKAybGAjZgQ6aAVlQgMRGkjQaCgwVCCUwcCLtAIJAwEYWOCw0iskErQFQAwEQEgaMiwIqN+gUBA//PkxKd3rDooAPd2OJABCMpIIukpSDjEwofMuEV3GClRtyuCAAwwaOOLzKA8zYaMjFAqNGsl4ccERSCkczwlMSHS0BghcHGQFMTVg0wkKC5CZIEqkR/XcgmXLAq8HXmHKa0yluS7VHAuGDQk0YEiQKCgqFgkQCoCPAxh4UZiRmChoyIGCnpcsx0aFR5LMwMaEgpYctojiFgUQjzWCENMAIhofJgkeMUARQdAkMEYaYCDImBAemo1tSbD3QQ4wQ/rP1E36VXcQvCkyqFPUeAY+/D0tLR5bViSh4sAorKxN3htOmQCEETOTeLPGAgxgoI6oUBUkXQWs3JiSlSKURXavWjkzayKduu7SwxdlkscKLYRGE0seqUMmvTNSjhq0/saswbLK2deOS/cp19NenqaGeyqO0UZkEuwrzUavy6rUpfqUOF6vQKA8CBOzfLGgMJwNgwrkoDJhCgMlwgOITTMOkCNXTHNYDfMDV5MZzyAIBGsx6GfY7mVsMmPNYGdRBGMrFmhwImDjXmXA6mdo+mxSbmI7KGni+mKgQm/AqGuKCGiobmXw/mIwnAbOMBB0sYMwPGxYgGBo4FRifbVAEKgJVVA1/UVXFdmbm5uU0+M7HWcwFL7+3akeLhVZqighnaR//PkxJtmDDooAPd0OCJEjACSyhd8HTRZuaU0YYEbUcDhj3AQaYkYChxCLEiAlDNOPBKICASQgDh40RR+zrwuMPtnLn+gSGYQ40Vbsre+CQySIwHAwBM4xh1EAFAwxiEBhEvNCNTpJUhdUCDzboUhgV0GpBkYhlxgccNCSApMGnAUGBQVehUEJdI6ILCxZTJFZuaPSXr0pqv41+5fXbXjDv9ZVaitBIZTLKSH4bzxis9JY3Zgq7LbUzFZ6AoHirKoDeRxmU0ECPNE5/49Ds5D7vVYCtVJJ2Oxd6HHn1P1mxUtZ+4vAbxTD8X4bi9ND9PSYY6z5WyqXq9+5Uy7Ysbr38MMst0v41a+F66qTEFNRTMuMTAwqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqowPQajEGI7O1oaoyVAIDRLCYMR8H0w1u4inc1pXgKlabaFSZegoZJEkZKmqYamGaEDEYQKiYzJQYCQybDEMZJOManmYZdiIazNGY7I2aTEoa2qidBHWDoiMwSMMciRMWArMDgISfJQLFCyJeVNBGtnqgj+M/fVyn4pHAnp3KORupSwXco5yUVoDm85ZSQzbpIzA0ffWJ13RTyL6GXMmqKm9phJQxI47a0wL0wI0zroyBQx//PkxLJhXDocAPd0OIZFUJMOMQOEmQgOizQFEkNbi633fRZLnyi1FXhhl9YAhURe5UzdYDWstVa8NCIW0ouoGDmUBcGBDooDDnRwQxqTZhCZhw6KwQNIggOhg0gxEy6ILEZaBogiQAkWWRQSohg4m46onFlTlyORvu8d6Fv9Ut6s57+5Lsa3atWxLp6lq2Zm/eq2Mb1an7dqU01a+mps7MzDNumn7G6tJR34tJ4LZ07zwsNYLNM6d6Tx5/otFbGHwLMVbH2JHyHaCXd7nMU1DvK7WrzuNNfvVsNX8cd2tdsVTEFNRTMuMTAOAWMAwGUxdmKjUaZDMd5Swymj8zHiB/MT09MMBCNfGVMOSRM0DWMwSBMmh0NISOMPhQMkyRBodmcw1mdZGmI5tnThdG7CXGF5/GnR1GQBTmLERmrUDgaujIIMTJYvTFgRTDEXzDADEWRoypkPUXTIQNfctWAQyEhNfaZrcWHIHKPv2ulymMP2s9mbGmUKTlbrusqevA72pdpyKdtOgRwknEOJVAAEKkxGQGwKWxpINOEzRzQzg0BE2cGVAVSAT2AQ4UPjBTQeyDQSI0hMMoRQcYI2GXJAQ0mEh5cmNvgnTDjmUbs5v4y1lMEloUQUzTAgcwEQDA94//PkxPdypDoILPd2OMlAkjVVyAALzgwNVMFRsBIoMPTMgUYHTDAswscRMM6IwIWmhFZkwSYoBmMhxnqYARYwc4MGAjBw4BHogMS1JgwMiUHD5YAhCBhAOiMhmKhymryLvVA47/LHb5xtsSdRFR46B/37eelgC1XbHA8BQ5MQxCIs8DN5U/kPsPYe8cFRiWPDTwi628QddzmxxtyaWUR2VRByJbLZfQOzRwLQwG3zSnSmZdSzr4VpRPzzdqSLw0/lO3XOSSGPPIvF25BIV0TMwuSXQe7GcOuHBUFwFHGZN/L1TEFNAJgAmEQFmZxoi5mOBcniUdOY0wOZiPApjBfmcgBmDwbGCxnmEwWmUKDGBpTA5pjCsJjJ8RDKonzF08DT1FzGciDPNdTAEfzEoQDFRcjChoTT5KjT4PTjkjDGlbzLEOjDAJzBo0AcBAsRCIEAoKY6AgAhKhEBhcyAQAReNAKlZacaB0VFtMdgdc6JaYcgpWmI8l8WYjgOl7EVDVN0F09nmY3afp+YCkLRpGzBJKkRuAASWRAIwYCCGSoBm4cYobmZH4CYRkvEB4ZAakYkZSshYMC1wb2hGpphlZ0YeGOIvFM1hsRj7dWmxt74ahqJvPH3ykqpok0psK0WXv+t//PkxPxzzDoAUvd2OCWtD6u2BlrRIFU2KA4wQZMqGQwIaoY2FGCB6ghgoIFgMwwNMBDDEQgvEpeYoECALHgdIktg0ctWKA5a0vMYMUhg6FBExwFMDAktE2RoFMEEBkGCAFYUVBi4691vrdSWWwx2w4KOLE1KWJIMInq5eVWVwmDNKgaRKwySFtIgJx3zdmOv/H5Aud0JUy6cpWyvXKoZcp95VPQw1Ockc/jGn8fSOuLYgpvpU0Z0Z6DZC8TzxB0aRrLauk0+TN9GoGtQRFZNLa8mlEFwmmiUZeVYaUS+HpSqTEFNRTMuMTAwqgsAAxgzilmYMSeYsKaR8CupkqNJjMEZn2rhpuexKOoiDwwAEUyWCswDPozzL4xiHwyPCcx+DMiL01sFEzgHU0af8z6P83BPs2WMMxqO81USU2yo8xhT8yCVo4VXEzrC4wyGssyEBAABjAQoFAhrauYCDQHDDFDACQwgEHQdLECAyYEEI1rfl7xpmJQoUA4OhaULI17KH30jwQAssBwgia2RK6BqFKpImDKiwiESCqMjZTBBUwEcEZKYUJBycFA4z0KGSky+IMMFjTjUEkBhKqPNo0iGbG5MQFugEQhYBeaPMfjzXIedBYsMM1hpuKuXfeaQr2UG//PkxPVyNDn0NPd2HH6ZSpkpY/yhzZ1hE6khULElDAQR4VUyYAKoAhsm2jgFwUHAAjBSsEBoEVRoaAhwEUajxZEwoNMQCRYFd1VcEAIJCkVUtG+BgGgiDAlBVHFbAcDEQG4K0AaIJ+IlOpDzM7bFkb3WWGbqtNvlgUArq08vl1G6MZh23A0NqYtrlKWWzEcZzSNzlT92M83ba6tJ18pAtFhrNYS6j9yCWZOVATrQa2BOp7lVVbGLNqnMyt4ospm70DM6L6ryR+cVp79yJ1IPRFWNHaG7Ln8fuXQK2z6NefjKTEFNRTMuMTAwqqqqqqow2jw1RVQ0Xmo1xa40HD0wIG8wXCcmL8xCPQxcB0BKoYnhYY6kqZZBEazIAYHBGSHgCAANKxwByQmS6KmpBenKN6nEpYHykam60CmHidmK8IGRCeHDT5HQwgnQLdmEa0GShCmbpymDpWGs6kg5WjAMAjAcC2DhXsEMi5AsgFS1NjJFoAhYOOhhHAQjNsDSS766ldqMjIQYs0suo34UBaA+6d7BktW9DEBklS8cGNCo7Di8BmBGlcd2CaVWblia1ObWCaNEdCIcyoeZ0VF7HjZUTSqzMfzolAAiJDhKTMyPN+pB1MzyBCcAAxQNGQAYMZu///PkxPFxDDnoAO51LKBQavkP1EQYAgRylhUiXsdd+GsUEXSLgdLxz4iyWTNov5dyyWJvI0p2W8Tq0XaisrW0oEupNB007maMOZSzZgAFBrDrEYeIwy8AuAkQgGN4IAlOxSFM6DgqYyHJmjbtShlmqm6szT2jMdooSv9/mhs+ZlYbq0Vo6uEQ2OtfhhyIfgCNKruJEF4LCsfYK4T64wxDrruO73H/VnYe3eQPJOOVGIBkLX4JvQw3Frzus6geQylpbTI287N35gKCXIsLopoIbI2CCmIQE78Cv5CHXsOfHJBVTEFNRTMuMTAwVVVVVVVVVaAh8w9MMlajMB05IIBT+aExlH0Y2KmyjpjpobKHgpaCheYcSGUrpoImbSSGus5xBecs7G7CY2Emym+avdohNh9p/GVAiZrq5jtFmKSSa1dxqEOGIEiapNp+KJGSg2ZWBZmQ1CQRHAkY8ZGaExhR0Z0nGlEStRmpKrCAj8KiDYyADMbLzKwkYDTBwEwcBXYXjlxZN0EoVtKLNFdVl9GXsVoVOrAYIDEwyZurmypJma2YGTmUs5wrOd1FGFBIGbzDxoiF0k1VRQANQFxpIEIuZ4WFAsaCYj1kPCwMFTHCgxcvMzFw4eZKgEMIAFLGHopt//PkxO9wtDoEFN82yMSYDae2OBnQjDdIBdFHxosMNUEYKYGAvGh4HBcMuukUnaCgNAJkhWXIZQ3NAO3Zdjqt/EFA3DXW7TkKkYA1CEP1ATBKVgkgg9hDJdx5uDZ1jwGnu4zXW4pHveh2fJ/nAYCoe7iwkga020seSSNOaq2ZqqwzmRVtqz6w08qY6h6roNZWvSUq/VWXzBUPvo12WNEU1g9rrgrNjsAwlu0CK7YC3j8xJx4GZW1aHW1pZVSxm0p5gz1PRLXwdKjcCLPXAjSIIaI1FyYbgVrM3DFSAoIceZd1CIgwYSF5skhgQwGQgQZjAJCLDBSUDD4Y9EpgoZmQx2YvHoBDYwGhQVmUUcHO8wQIjKgXNdCM3emDgjqMurk0wbTICkM+yo0AQDDIRMTDsyInDLQHMDkMy6lzQxYNIxMzeLjMd1NqjcDEIzwaMVEDBW0xxkMDYziAoEghhIcsxOMQlIVBiQBMPAAMOGFhpgYQABUoTjFB4x4cAQgDQcwoKMaJjMjozIWMcCGsmNDxMGA5MEQoJCxibqaorGGMgCPDL2wzohPkDTgikwRfDjs19FAxGZqJGDDwXODWmY2M3KqaZ6mmNi5twwZoymloQdPOqvOomJzAY3OAIMiCNgEN//PkxP96rDoMAub1MAj0JghCi0AwoUoDCQRAaYEeoEXZZsjYFgJkx6KyZINJiSYwyI0zQFdxEgIrBjQZjFR1IQskCwkBAzODDFEjSGgwCZ8Ot4eC1S4CKaV6YYjDNxLj3Jp/E+EzmVv45YoDC4FEYtCLBQMLUvU0EAYvbJUBZkSagiKAMFDQAuGypf0MJqFuFBVVlqO/DTYG7pxxlYd3oKway8Dd3diMaf1k0seeXRiJyiNxiPRCcoZBG8IpFIxYicniz+W4hblcY1O5xtmECPA5E1CXHaRPXYRB24AlDgP61tOh/IzD8ERFrbRpYxOGFhHhnoJoXfkSTEFNRTMuMTAwqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqoKywbJM6RhQbAETGpGMEGHGlE8zQc1QQKiTIJDHMCQ0YAQY9yYIIQKzAACa4zcFNBICa48Z+IvgEAQMUTJMIEQhFARljgJbmKhGZRkJI2wwBVzNhkzSJ4GI8sPPcxNyE1UuEEyHBVjfyus8Si44ct0IABUwNEEBTnayHMAAJZDzkrtf4QHIltMMwxhQKScRlVgy0VmxZhTqU0wlm0BXb4Byn6VVLgIiobBcZeRAStMccnqmu0BEaEthdBQtsDDXZTyZ2GJ//PkxMRlzDpBVtY1NAuoYAaYUEOGizZpW48jAZ4wBU05o3bczBkASDThjSlzIuzxiQSdCPyH5riIQ+DooYeCIrE1VAqABolgTMmYNxXUrxqr6KnYk0xRtRlaDqS5YItAjaBQjqwGiUgkSZHghbIgDBAcSHR1LtA5jZcVVzL3Qae1+ypjKoyzqZlkKxl+dJQRiBpLbhcvduHIbhyI0T/0kZi87Jb0EQmG4Dl0cnZiUTtJnFKJwbC/GyuS7sVcKMy9ZUVyYc+j3y6CpQ6bnP5EXggSBbb8tZjVmCW8ndO5IpRVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVEQgAOBQIDF4YDDAWTOs3D8btDEBUzDIcDHtqznFrzR52TRpfBmQjfyJDUIjwh2jBteTi9TTEInAoGBhCBRpEdhkkFJjICYKBGGMAuwgp/ASsacfAazC5qZ6ymUkh+TwayTDSdWAJOY6WMzS8B1R5SmigiSagLXFDRYcM3ooxOQ0TZ00JTK3xepqFyJKeTigVaSPDfLclCYbJn+AiCQzCjSUAML5phNYUsaan2lO/ynaKDgCzQ55bsUSvA+3VmFiqUoRgI5b9d//PkxMdmvDo95u7wyCZQllnJSLlfIGrvO/j/OK7TotAcagjKZBIMaGYDjcAIkLwMgTKgQpRyGWlCEioEQgVURNd9ikibPOwiHKsPQxYuUliV4v/ADbvGu+bgGLRdwH5e+HbUadCBF2MTYpC6dfatsLfeVL8i9O+8NPPDEojMNv3DEYWmgYk6gDV+DAIiOQluoEZwo5MQV4yUBTjoUIXQaZ1DAveo8nqrptV1qbrIXTGgSFUyAxogoMeCgDeeTrobm40xAEWbM7b6wPVl7kbooAhumvS/GH5HTT9NBUkty+a0AQGQABeMMMIcxyE7D7SGcMeIEIBERmKQiuZ5TFRhTiVGIgDqYQjGRzmALmQELMYFQb5qhQ5slJxlQHZh2HJkYF5pyE5roOhgmFZioJo6u5vMSxh0JxjqLBs7pRkgSxhEEJl4jJqEsJsoP5hmCAABcwNCAyZFYiECYBIQZ2VBhIliXGMKBy/cAKZAIFS+irKmml3ZXKVHS2MUnE5wABwOvtHpPYv+jy1FHQSG5cJAYyOiRQYSLGtnRk5yZnJLOMeER5uNeDzJxIyk2BIoY4MGDgxlqEKA5kImCi0wUVEYqYCIlCQZIvmnj5gtsZG/mFOJpxc2ppg+FAdW0aSQ6bAR//PkxP94PDogAPd2kMmACIqDjQGrKiiuseBm0LMI/DoCJEwiDjBhQMexIhLflAqAkkBD5hBSBTILhxgA0SgosTGOCKpzABsSLSUQHhNBlAAra7tRkMzC6kQa1OO04bouTLW8FQBMNTFKkMBWJgYBSMCwSh8XCbsslFRH9S2UjoIhe9rjokN8uWIpLFpmFrpTlUxjz0RKJwqhfZuyYzckhVIInFtppjLhr0oU5i3RZ5dzI1NlHbLRom4CNVA5UDM6jbDqJlZdl2Gvy5YaBmswzJoRt7YXK4rTzNWelOUSwqRPCdqQzWlNiNw7jeu1auWABmDACmYJoURhHC4mOTV0am+H5g7jiGAACyYSAPpwwelmgkNSYS4BJjmsCHoSzka5AZRhSgkmCwCiBBPDBeBpMAgAYwcwFzCGCvMxoMUEAZCICMwSAtzMAK5MOcAs17bNcLTm6w5Q+f1fhkbAa+DiwGycUITUhUuM+5bkwAffVpsTaCrEpNWJuKNLrl1pe1psLssRpqliHYMYbDLBFexOCFvIvpXFmgwVQRCRmFzAwQtMpTjq4YzEUxjIyzk1BslXmSEGbJmeLmcEmXLG2WmXSHHEBjYQ/TJvDRohyQajceuiaJOawidFKfWedQ0DyrsG//PkxPFx5DoYDPb09ADB6SZmQktHgphyCOJeJB8wBszapahgDZqR5gGBkyAKoidowLsyRIx6cMSiMSZwmCA5ngYJAI4CRBMGxWToGgxMFZ++i6IxI78blMD0degqt3rNabm46El1o1Drjv2iuWtL1NnQTNeSpVuR6RxQAp7tu/TjQ9E+zsMs7ibkPy/MoqWY3Zf99LD8QJGrT623vjEel0n1LmXS6HZp3bUnqRuUxiTZ1ZTDEzeygeQuvDTdH6gCkeBOppzpZsBZbI3beCA5Q9cZk6q8AtxnYL+zfh2CZyXOtdnlgEAgDBgIoD2YD4CLGEFh5pudZMYYWODZmBdAIRglYVsYQc+RGYBjQZhdYKcYFIDDmG0EkplGwP4YJsCtGHQ+mHpLG5Y0mMQqAQLyqORpb2x1ItBlgARhiMhoC7x0aPZg66YIEgUDMvSTJCBEhAgDRQ2E7EAivIwUQATWYIELMQkiwYEBb7qkdh+1VF3M4dBt2cF+GoxOXvrm2zQncbgyHCDW+VItKlZUIALgBGTIQUwYqMBXDHxceiTLSoFAZpBcYcUGECYCQjGT1Esw4JDlMHJYWAAxUAzKYSShY/ARKBV0yFmNzbSs3MgkyqVGexBsBQYGMHPIZjomQBRn//PkxPx3fDoUCv92iMMmUFZhAAZcImGhKVAjOS56AMRhgMFRwCGnAtaZWJGSB40CGLi8lMDIzHS8DHhhooYGHmECQOPhUALOlUGnFDACDRlkhiQYrajum0oJKHvmoYhpuDaULoIoM5laaYIAC+DGwUBphvxAaezkOQmWXubs4aXijDowApvHnWDAJYJmbL2XKZvrLGlSJhUAP9AEw/8fWAf5+oCqyO898KlVFDWNPQ3dT2MYpXmjEZZPNxJ+Gt2dVHAgZAHcdSRs0g2o2Vt4LZu3dY7wQdjB1K/zDIdXe48Rh5/HkiFNAcP14pD8flCDEVhy15gSi3ngkO2Yg4QgyDiYDoYBkSwzHMyQYYxQrxhXBlGD0BeZfzdRtGHNGnArgodzGlizeZJDIACAsBxgsLxrGM5qEVRgMEJQHZk2fp0NHhrgWhiUFAED0x7JcOH41iotSKoEExgAw0MGQpo1ZMLR5ARMcEA4UXwpXfAo1FovgqdmpiBQkIaPH5VSWYutNdEOYM8LQKqsXSIYaj6GB0zy9gEGFVeAQKm4oXJWJu4ZiQjehjBiQ0IKHJgQZK/NrPAIEMaGIZG8NBBE0IQyMM0DM0+UTrGWPm66HeMB4wFOjDOR8ibYICRqHUwYhhsL//PkxPFz9DowCPd0jlnu0iOxUcCOy6JMeRRCwBWMWCqDiw8DCAuDir4jocoDg4EZUWuswBZ0EPwuAMUMQGs0GiiNBesKgU9JIUCAwO05jwMBGcWGmEPOrAYYsZwUpNOkHCLKYaP5hQ6zmnoIy/aUxZQWKmDCmNDp/KwBYIgEe1rRbBW1CtcigEGOysOyJXjlt+yhhmnSfWD4ZhSwb7xeHI5N3IYfKSwHIoYisD3IEoX6UwTAt3lA3bmk513tvB7SIguiq09/6juR1bKp0i4BTDQTs3mnbXJDkUchShMCKR+PM7vpiMMkNNB1eB5/SYBwwPwHzCECYOEdRIDFWCwOQgBTMBlmo0cCUjFuDFMFsFYwTRAjOVa6OMAc8wzQVTAIAUMGcdsxfB3TAlA2TPVTMHwwEwvAaQMEkqcwFhNzD7NXMSYREwrAd0qDC0BCMVcDMBTBMCiIQK35K1fr9jiGaiQxh22hGRAKFUMS0ECaebWX6zGBVY6l7RRQDAAIzhnDOYbAwY/LjqqggHJlcVBxwLChQUZIOCAcMGABBnxkd2VmADwODQUOmmNEEokKCGGmxxpuLIRigsYcaGuWREWl4ACVGYxBhqWYqHAQDMLJjD24WNQIDpImDhhkBuYqAGLG//PkxPR3hDo4APbxGEnkYaiGbARjIUWmcEQBK00tFKi2RbxJESYxdAG+6AFAOzkLJR8YnGWWofqOpoL+UpYgMpX8CQjMjCNlpboZCW4FyQ0QuDGphhgAFEv0CrAdDTSPhdgLFcwa2VEEgDoJIUzcAGx9i5AA2Hi+AQOPGZDxQxCV8O+mo6qlyIS6Erl2tRmWSziM65lzp7P01t5WHs4Zu6D9twbEvpYRn21L2VrfWOwF/6r9oMuywdm8mb544CV8yNk6/m7rnYTAq9lN4bYCyOMwzGGysoZRZanG2ePSUNSfYQp0ulTNebJWlgATbprOxDjpyNJ95xYLhEoB4XA4MC8QUzFHJzGlCBMA4AAwOgVDDtEwNwQNgFC+GBiBcYTwY5llutiU4JsUMAouGRF6f/5Rm4KEoFQiMYQM5M8AhQDwHMkBs1SNDhI/EIhIREY/Vx5NGmliIQKF2zH1g04URFc8cFzFixYR2IyMhA8TvZDjcTEBFnUFvyqiEECg0YWojWlS97gURcsxQIMIAk9oAMfFjJhgaNEABkaMXbBQyDgIEixsMEYKKw6BAAAhRkoUDkgCAQGXwaBmgqBjh+rKYCxBzGYcXr7MTJgaRL4BwmHBDFTGQIKBJagKhQGAhGAA//PkxOlwtDpEKPc2jCDkdFdgoGIQeHWlKBAIGc9iKeyHZjzNWuQY0poUTV827dmHOCsZm80jyz5fCXrdH7SZSOWip9W1mC3xCCCwEYABodFdF3VcrCF5JeKAqANvwYFJ8poFoWurmVwpchzQDoqspS9FAJliw6qr6Myi8ZfivALYoGirlSCrYa82FvWnQ5hDzfRSBn1fyOsYSbZE99DKW0f55840uZryyogxF1H3flrT9sii3xd0WGPisK7ul3wJkw2tPs5Yy+ky7tM7biP9C2cRNqcMO47TQ40o9I56BGHNCbaKrZgqTEFNRaqBgGAFmBKAUYGQHZhChkGYJPQZDYiBhNASmCGByYJI9ZumtMmN2DeYGAKhg1hrmbRSObQhORtIAGMwYMGg1thT4RWBwMa0YkJ4Nn5xwqA0KmBCIZysJ/DKGzA4Di+UFMxwEzXoZDg2huxgIIYcTGPvKKgAdOBSCBn6dMDJV7xVoSgy1VxvqgUn2utpjS3RXKEE66vWjCIeYgcuI0gsygw3hs0B0zEoFECfWCV6pwxUCaBjU6KhhwjtBdOKEAVeBJIfCmqvnTgmJImqsGSonAfG+HGODmTAhUaGQQYFRtSsCgBbCVKWgqDR9UXLXK3hcMHAF1KW//PkxPRx3Do8CPc0kLI2rP48SsTBFNFOmdFwmWtzYa6EPvjIG3axInuV0qFHtMVU6tSKLarCxsBAVKmJoB4IMEZLZF6DAACoBMGISCXMlUkkYQmXMS+WMxcECwIJHhK6AQAScW5Dae6C6ljXGsv8yxj7A49Ko5Cn3pokwNpbImzQA/EQdWC7C428TgYSsRd70sPVUXGm477A2YM2XK1uGHRcm6uKFOqx5k7UHtam6613EXpFIu1hYNU7zJyXl3tcYeyuHmYS9YmnPch7Gd3XAelpM/EHFVubI/jJYFXW06E1TEFNRTMuMTAwVQoCRQBQEgdmBQG8ZB84RrGDTAIEkwZxRzA+CKNKwcY0nwhTCaAcMF8CYxMjBTVEWJOhkMxOBAwaGGBeZsv5mcRhAyQ7mPlWdIaZosCGBACYaGI6Fz+SPDHGCgSIwWaTKZBQxCOKzmMVmCICQRdQWCmSDhixKxczOouWfVjvSF2WzO5fiKAlVt512yiEIqF4Ut1TGnBqKkQ5fQgnnNHAZABBowUNikFjJCSMSaNAdJGAjFhgZB8hADAkww5cwsXABw9qE2VICGAQSBy8zxYQH0qm4ITy5EErmBIgLgVcgJEnW97/jIIGgWVL6RATSSCStqpqyqXc//PkxPVyLDo8IPc0jJ2Boy4T/QqGIGa87DoLAxd/GsqFtgbjGFVRkGKhV8Kq3gIFXADgaaZb1qQECjAMqg04TADRY4WiQ/FSSCFNcoCgIYEBjBAiwECgCEIDFslANKxZJeRpSli42iMpmocT6aMzd+2et4zVi8UZOuVsLI0NVFFjMsauqBfSw8HA4OxhaKAkaBJksGLtN1bAuNAY7bIG7rrTRVslJc5mMQUoVWY+vhVKNsNQcb9ayCsMJaw6X+TbdGfcdQNTVUcDstTjXswdnAEAI4pmrxV4g0wEkBs5LdU6TEFNRTMuMTAwqqqqqqqqqqqqhABfIwCQA0dgsBSYZ7+RzdAyGCUAgYCYipi3himD5fsbrItY8C6WzMBBEMnWwPpQHMEAbSEAILGBxbmd4wCwwqiHAYMaS+NWRtMHQNBgAjgcGYbFHBaamTokmAIABQE0HzcsAz7H0bTCrOoJLipDgFODgXndZf5cELiCyEDtmagDAZ2TS6YaDHIalssa4qqsCOCmtyYDQxIAHBDOLCmzENPOaFgEyzMLL6JGGaVA6Ppe82GWgBUgWhMMU1mTeNBwogHMpJtmcITTIKGBmdlsEIl0w8slS6MqNiIkWFdNXDHkKYeSOUacB+FSsBbi//PkxO1wJDo4MPdycN1p4o5T2sHSFdJYdpTwqWl9kWGtt0MBAQBrwYa0vBAg7RZUqqBYMVDIkWup8B2CTK50f4TC0TGAp5KBIJS+qD40A5Flx4RDNiUQDAq8M5bLW7JBuG9SunhpVDEqUK0BDFEkk3k4FKGEFnR0Av4RGiwzCFelCoXHQ2LwLOd9QZjzDF2StOhTRTdYwgLR9DigSM6JKC30EiIF9ywUo+ierenMYQTepAqeWanukgXlEQaVK+AaCXoXaX2LsrTJToDLZlsA4RyXIQ0R6UrcFZxKgDQ0zUd6TEEwHwDggGEwVwIAUM4Ygs6hxsHZmG+AyYawNBjEiqGlL+UdVaOhhOg8mfhMYoUhqJ8HN3sYpDY4ACUEBQ2mrEOTHVHIABQKCMzCoBphGDwaFg2ZtXJyANmb1UYSHRtHhtkQUmmHJBwQsgYgaEJi6r6MvRMJTgQm993gWc9tSD4wwLtPDbPK6fL6taGgAGJF4aanKwhnEqExW4DAkfXNfktC5CE4SDTsMxWdb5Yr8Q1LHdTJMUNUgSiwcBY4PGgILUDUBYLAK1XSd6SQNQxCAZbVVLFZZIoPY4mkx99GIxiHHIYgzpuTM2sphtChJd8LAWgIpqvVRREGA4XGBxYC//PkxP10JDosAPc0cB8eEobGTJGFFGLUGzVCNicZONCnHMyQbkCophAJlCIUKmQHyVEUCDQsAS2KoQwQEwIIxZtLpTYwIcv0WmCADLBgQnmvyUMGcSGhGGVhQIMsGCDBF0pzF4yQOviDEG27PABgRclnisYoNCwUSDypOsEFVVCACjGYgCAgivmJqUCw0WCAoUn8l2WZa8gDL0qFyhoCDS/1UEwC5dAY8QWqQtFCACBKZIGjANKF4BUEOATCAW5AYUlOYkJTKKqxIghy1uaygcWlJhgKYIFLEx4mAruYkKg6TEFNRTMuMTAwqqqqqqqqqqqqqgcQAYAoHwUAvMAQHIwEwWzPP8RMRQD0w4QBjCiEQMisJ42ShpTEcATAIH4CBhMW0V0wWQGzLA8MCRwUNTFgMnKvQ+McPAwKHicBBoiPgqhGahwELQxZM6hAN6mEDIBMjJDo1NLMjLxCKJdpDjBoGHnWBqQam1dYBdMCJwTywiVTVETEpEhEe2DOok8Z4KE6MOgYQQiTQ5q4ZkSml6maMASEglgcqZXFJO7l2WwK8cWg1XCRa3zFPPmNDc3hiIQtWxRKseHf+NS2Jv/b3Yu6opyMagOCGGL4ilC3FmKC641d0DcxoNhAgKLWTAGB//PkxOxv7Dok0PbykFmApiWgkNqzc2HJ3DwCPkTTGYeOghBRYUUvViZy3YwgCGVhQUcdxuCEhDJHZGVfhiHCAd32EGKaUchddIRE9iZKMCgBwldZCM2FB4RkglFKgcCQyEIZc9egWADkDFKQpAR6WQsStxY4KDHDF1BYVEgvA+AAFTRM1IsDOKWheUwmWnLDg4FIEIDKgRMMERDBYwCrkQANAR5JgQue18tYPCL6GQ2dIwhAhehz0HGPDyGTDiAJ3EL2lNFQlpDo3qPpFpHKdIBFZWHp0RZU7L1hFgIGYE/1AAFMKYQYAwYEQCRgZALGCeCeZFB0xm+jMjoDBgnBkGFkIiYzZFBopGQGJcAwBQCZwBhv1Gnb6mRiMHKwtgYzM5lsSqXGAh+EJkHIcOEBgMRAABoaGGx+Y7DIsAhgHjQhMVjUDCow8GQMTDK4HM4K46NADWxWMpD4xGWzBI6M2kt9mvBYOYsgYAM2jiAUCY9abUqyMu8JFQSDRGQTkgYaGGdNm3nmPJGAVoSmCEgMs0WzMSBSMMUMWIEEEN26L0WyydiaCABAHNY2s5BQOJlUCpsCA6A4EjTKpTCmAh4ZwgZQEFBCzVa1hGmVY1Rxh3J23L3QpYvKH8mJuG9NILeJ//PkxP91RDpGMPc0eAjkMoTJS7nl1Oo6b/ssbBTx6H4s9cgdy1MxuHaz5ylnS7HPYYwGYTXf9lEbSHYom6pvHl+kgKGoBaUhiu51IsrwFB22aOpNlDbMrRDQXVSWFacHAFcJeJaKWqSX6pgDAREEUNUmtIdBz5dNLVTIwQhTktyPA16GHKhiNUSchhAi3ktlACgIRGgcQTCkqaZigSSi1X/UUBQgtYDgcdT7RtHibWBkKLA4ZQHsQREXyyduEArwUrRXEQBSbLmzLQLdmFAtnBwAFAEVg4oFRpcJ1WkIGGBEiwsAAaAIA+MEkCEwKAFzARAeMFpUA0UwpBIDowHwqDBKBWMUUrc2GCHTC+BxMCAFwwNAaTF3ObP4kE26KDGo7WOSNczaFLcOjIHMPptADKJwRAwxsCgERm5RJBoxQVTDAVMDghS4wMNzCsINAjAOC5gIIg4wmKlMadApekCgMLODOUwURRNIS5jR5zCTQ0JaaRgkhrg5b0kEoNGbamIjHPbGfGFUOafeesMJBklrgWBM7V6yxzEEKxggO6peAAAKqGK8jGBDIBC3xbgwA00Is15MYNh30xlE4o40I9uAICr7XS+jLJ3K3OUsTjUJkDcI63ZY6fUfXgkenwWebMpY//PkxP12TDpN6Pc0lJ6OWglS5fO858POKoK/T6ODTS2GpiV1H9vzVZynxn5JGZWwBtnvaA28FL2XCj0zVOcuCiijcoDYZMwhNULhi7LEUQlRo/CoJAGYkm8ZbMlCLORXXakSgsZ40hatoIOgkMBBQgAgEWsMVT4NQlwDHlQoKCAQWVjJEEkCAKDiJCUVvARIAizQGQwmPHQUNHiJkwBpRhhgKuDHAQALDEpQSQdHThgg5e9JJJUVGraAxRF1SSDcVREVTe4GAk8mhVX8GAkNIRSNNXOLgIKkSjWyLAs0s5tS2Lgs+QYWSreqMAEAoiACLVmBACMYSqzhjxhHGAGAeYG4CgNBOMIVfcxjgpTACAgGQOTAmHUNMgjEFFNg4CgugYJoYJhghLDwNbXDAREzWFOFLES7hVADGmZAUrEooWUMeRjIwBizMWSmbo5nQCCgExUNMcJjO589jnODRDT2k4vjPddhEJJPl4gaymeoACGWomFkYVMAMRCwMFQMztBMAaDKDNqBlSobZcHEK4QDFxhUXLJGNhiWyMxewwAFMFFAUJCAKMiDAKEEAKEBqi5hYOXUaEDQcxUbM8LhGfmZBpiImaWlmFGAk0COzQirAI4nWVgZL8Du0/DW4bghVNFd//PkxPZzDDpMAPbw3Anl01qRlJ9OsEIVIzFv0V8WXLGh9S7KHHQkD7x9lU+/smie7M9Kpd2L1J7KAoJfZu0WdxudWMPBxyWkNLf952iL5cyFwgu66TVWZRd6XeYitJeRdpMGKAQMqe9K1a65i5KYhhNcfwSAnYBlMGW0lWQDB3YS7KhqgIKkvtTVDgRKBNGJiEZABHkFZZ6F0MjFigQIUCxodEqkHAQBK5L+F4i8zDmTorrCNiRBehHMQKdp+KVqgISzFojOmxhzWguUW5L2F+1LG/MQR0kdTWZA1tZLkIXOsnnVkBewwDwKzAaEsMcYsowlAWg4DMwIQSTFYJKM08ugw/wFwuAuYPAZxjYK8GcGSAYioShgtACGD2K6ZKwe5gLADqYgEDU3/tNpbgM3ISzAwYyE6M0ESIRMAGjRkwUBzKAt+TBhgzkjAJQEKQKFBwiN8Xjr5w0FIM4EDb6E35bOxuDjRg6ZQBi+YO2G2hRhgQYmXESYcUombEBlx8ZYGGHpIDAR5YMbXwU1HXk5vyuY6Xm9EhQOch2KiwcUAS0xCY0JwwiYHARYuaVMZA0BgbtKalszanwQGUEMQjDQTYzMMTTHzaDzgDgN5Ou6EZ80xYgJpgqBNbTVa4wVYJmS//PkxPx2TDpIAPb01Ae1VBOmqHGgwul8+xQjUNLahcEYgiCjoKSLRZIisneipae5f60ZyM070W9vq5PYafSbfmAZc/kcfl0YJcaKQVDzxvu+bRoi9z8u+4UJfl9JI+b/SuUwiINkZXBbSHckEZaW0tpNMtxPdgOagylE06qq7J1lLxbk6LH1hBIO3RW5oaTbriMAkCuWTPsis5KZsMr7TGb9GVcoGAqjR3KA/VbXkQzMABS5bqlysNQMYUvC4JRSidIus0dBlIlZxUCyEuSuVAeosyVW5sTImvl6klC5jIGRxdf7kKXPakPMqkxBTUUzLjEwMKpDgiMAYRAfmCyA2aC4kJg/AJGAMBEYH4g5jblaCQYJg9AUGCqJGYjIuRkbEomHsGEYZQXRh/DSGSAKSYc1FZAYyHG1A5q6cFjgzw8MSOTO1Y1oGM2DjFAcBMRj4yYSDixWYYKGDkBgoqYmBmLGQhFzQiUzIoAw6ZWnG6Kp25kd1tG0O5kvQcfPAJsDnM1ZANFbDijwx4PMGgjLC00qTIq4wIZMpKyCZMjEhAlGoJZiYSdOOA1UzxyhAsWEwjIzfCFljaTMFAwCBAYVghmZiBCXB3AlUwFEllwq+PmnBsOaDOxzxHMWVrhlwOCK//PkxOtvtDpQAvbyuoqlhIWsSlk9WDWDMFViaEv8KCLFLaq1DxhnhAY0KGgIBY2hYdHAmCjKgz7NHhFJSPHWfiYgu3DEFSSBX8fObfmDF3P0z+kmrNVz5ZJfXJajsIdBOHiN0jf+Myh5odlUvcFutFKpdLWvPu5MNQ1fe1tIvWZk16Hbknjzf2ngstxl7S4dfqcXa/cGxp73+h91Ja9DtxFlLXIdaY/bJXjjnE3l/5Lb+mhb00z/w66atygUNQI90cZLL19Mpf9yGmuS8m1tNXZe9kfSul7Q3VfFyYxA02zSBIBxgFAhmB2FUZahSho9i8FQI0wBROjHcSbMhITUwXwPDDgI6M/Iw8yBhYzAkF2MihGIwQEHzMwHXMOgcYyzQmzHQC7MLoEcwQwVzSUoNflwwkiDLDqM3M0QhUwOVTQImM7CchJAAHwOXBkcOGVAEaDFoANRgwqmPD2YmEBsYQmOZ0ZVjBraiGgGMd1aZl/fmy5uc2Zp1MgHWRuYmeBntWmXHAYTZJr8WGkA0ZOKB1lHmX4EGQs0hFzPxGM2iQxgGDGBsMagsyWhXxsspEQOeIMKEOYHMIPGspjDxQWEUhGsLmDNHzTkh6SbwsHZhjQCdAABmQRnnAG9kgqIbkSa//PkxP93LDpAAPc01NTHDCCg8y4ExoBGpPBdcTexCeo4n8FgD8BxtlxMVAIkeLDApcYAAM8MqGSYGQxbkhFJBLEXQoU2qwyeriPupwrE5T/ySSzEKnXKl8ppI1NRbuE7GewDEZTRZy6enZyPRGYmmlQPFJtxo/D0Rxft/JtjLgy6TMdct1F0ZvgzN/2uuep9uTX3/xh69acu0+62WYshj0OSttYq13cOzMtfWBZbLmtXJdC5fBD0MmXU2Jsbxu6wZrkMvW1hvXalTNGlROGYNWa70qdyHos679TNt62SSOIv+70cgdsMtd3lJYfMBYBwwGRXTaBWIMU0GIwHwRjHuRqNOMZYwxQAzAWDQMlEqEw9gHjAwCmMiBHgytRGjE5BJMiE2c0zzXjNFFMqtM6LeTvj1NqGA25QjJa1M+HU12jzNDbNTDMsJcwGmjFybMmEExObTLKcAo8McpUyWYDQxpNoC43Ioze62My0UxOgT42cPOXk6qZT3PqOnZM41BjLIROPkI41OTQR3OGjY1MJjka8EeOOCo0zcdDSo8OWvAx+NzEprMLkE2YBzBZoYkZyLhQRNZMhEmGFC4YThhwYgakSaZqKCEYUrMgFghUMoHzOCIxc9MzGTHoMEuBhhIk6//PkxPV1JDo4APc2uHFjBpQsBj0wNaM1KSyoQCmAiwWCwaAFxkAqWbgqpMcR5MCA0FQgeKoEDlIVCl7hQeJjIFAQwAGGCbDE0Q4jTxWGT+pYnDjXb0z2U1ojbwrRb7UMWt0muV6+FbtLuZoI1jZlUi7QU1LEYap8oFgLFsEaeWIu0uudhDSZqBIs5MFxSNNRcprLXIJg1ePGmrtcZ0GiP9D8D1ohNQQ/VemcKNckLfP9D0qmG5SeFxqLQHD2L6Si1D0HxKDZbdhMC0cTmZiblUvjURiXHWpZY3F5ZuGWQyGCaeNS2Bs4Nikrh18VTEFNRTMuMTAwVVVVVVVVVVVVVVVUlGAoA2YEoLBhMCSm0EDaYaAJ5hHiUmjKOQYaoFxgEgoEhrBi0hNGCSGaYvYExjHBHmC6DKYj5pZi9jhGC+AoYuZP5iviJGFOAwYMQChwMGmghMZyZRrhWmQgmBQ8ZTU5ooKmciEZwDJmlAEIcMXGAxeXSQgGSDOaNXxiZVGXIEZCp5qCdmM8ib4/RyxJmJhSdeGx18VHBSObhSxppgmmk2FX+Z1jJoqAgR/m/EIaTUxj0jGiygY6HploFmJywCQSYmC48Bg4koICqeIhAqU35rAkIgOOEKyxgAOy0FCo//PkxN9sjDo8Bvcy1BMwFFrGIaMGg9kCQE6YCjLAwQ+thHVeqb7yPs8z80MucWhhSumVrRaogu3dBkHGwMloXSfkUEDhlJwQuyXNJbq0yVYyy7UvWe97WrbpYrSS59rz/SqB47LJi85UtlcAS61K35nG4yNwZFHZrPHV6rhS0lHKLUp7TVIllajsViMFPzS1HelWMppIlM1qk9KqaHeT+dSRRmjsyqX01qX0lPVi3Mbslm6tJFolnDLkz9mHXlmn63GYBlsUgeBI1nGpuERCGpTdh2EUtNR01aJT+FedtwyqTEFNRTMuMTAwqqowIwODAaAKMOtCA6UikzA7CyMiRqEypwUzC2CYMv5fwzrijTCkHgMhA+kyLhgTBkEaM8gXIzAyqjC0QTNQsLY6dhQ6v+8z/lY5Nh4zZHs31Mgw4EA0YXIx+X8zTbAyiBczrM4xVNozYMYzxAQwFZ8xWKAwcIk1rcIxsNQ2ZJY2lqkyITQwiBQ/UPM0kps4Ibc7Sls0yR0zOO03WV4xRP8ykYU45eQzNOIzTVgzXTAyPHwyOAAyNIwyJHAx5KIKDWYnBCGGEYBh4YQgkYWh8CQjAwamjQDIkyBlWUHBk8wqMKwJggpkQyKJRAAhkxZZ6jOvhJEb//PkxPRxzDogAPd0uMHg2GawGDWA2UCqMzQwyhUoKprBgFcifaPRcWCjBBUAiIKwpgCStCUwcJBBU0AkwIhrxhQRESUCcouEnND0B4P9S0jkxqo/0N2fkFuIwC/krl8ESy3bvbpqHXw5TQTPci9LFq/LliTuhZt14IravSy6/kStWoOqUL+0FX6WlqyCmlECUluB5fHI5KYJjXaKRzczR19TMtxiNevKoe+7EZDMUdqedrs9LI1uVS+guy2apvpqsRm5bhlTxWcvQ5Farzw5exkr4yuvFITD8YjEtpJvkX7VTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVZGmYMYMBhSBmmcG46arQnZhLhPGFgwEYnYCRgPCZGPaM2YCYB5goi4GQOCsLA/AIUsxVgMTBfDIMfwWQxKw6TAtAZM2wFYwtQfzBOAhPPuoGFE2WfzZhbCh8NnoQzCBDAh4MmDM0ICzI61M/FcwmGigym3r2YSDhlVMmUZUY9ZhuLfGiQOYWIBoLBgaRGahUaYqpwghm9SKF5Mb1EpiE4Do9Mjg0LkwyWRjsYA7N2UjwWUxAYiDGlEJlQJYymyolgF4x1kjKnakV9y0NU5iyS7aY+VA1lBS9SRQaw3oCFK/h1msCMhp//PkxOZufDokBvcw0BSgLHWCMEwLBGJb58yDqlw=";
    Uint8List byteArray = decodeBase64String(base64String);
    playByteArray(byteArray);
    showWebview = false;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (ref.watch(app.model).state.current != app.State.waitForLogin) {
        switchPage(context, const PairingPage());
      }
    });

    return Scaffold(
      backgroundColor: colorDark,
      appBar: AppBar(
        backgroundColor: colorDark,
        title: Image.asset('assets/images/brilliant_logo.png'),
        centerTitle: true,
      ),
      body: Stack(
        children: [
          Column(
            children: [
              Expanded(child: Image.asset('assets/images/noa_logo.png')),
              Column(
                children: [
                  if (Platform.isIOS)
                    _loginButton(
                      context,
                      ref,
                      'assets/images/sign_in_with_apple_button.png',
                      SignIn().withApple,
                    ),
                  _loginButton(
                    context,
                    ref,
                    'assets/images/sign_in_with_google_button.png',
                    SignIn().withGoogle,
                  ),
                  GestureDetector(
                    onTap: () async => setState(() => showWebview = true),
                    child: Padding(
                      padding: const EdgeInsets.only(bottom: 20),
                      child: Image.asset(
                          'assets/images/sign_in_with_email_button.png'),
                    ),
                  )
                ],
              )
            ],
          ),
          if (showWebview)
            WebViewWidget(
              controller: WebViewController()
                ..loadRequest(Uri.parse("https://www.google.com"))
                ..addJavaScriptChannel("userAuthToken",
                    onMessageReceived: (message) {
                  if (message.message == "cancelled") {
                    setState(() {
                      showWebview = false;
                    });
                    if (message.message != "") {
                      ref.read(app.model).loggedIn(message.message);
                    }
                  }
                }),
            )
        ],
      ),
      bottomNavigationBar: Padding(
        padding: const EdgeInsets.only(bottom: 48, top: 48),
        child: RichText(
          textAlign: TextAlign.center,
          text: TextSpan(
            children: <TextSpan>[
              const TextSpan(text: ''),
              _clickableLink(
                text: 'Privacy Policy',
                url: 'https://brilliant.xyz/pages/privacy-policy',
              ),
              const TextSpan(text: ' and ', style: textStyleWhite),
              _clickableLink(
                text: 'Terms and Conditions',
                url: 'https://brilliant.xyz/pages/terms-conditions',
              ),
              const TextSpan(text: ' of Noa.', style: textStyleWhite),
            ],
          ),
        ),
      ),
    );
  }
}
